services:
  redis:
    image: redis:7-alpine
    container_name: mini_etl_redis
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - ./infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  model:
    build:
      context: ./src/model
    container_name: mini_etl_model
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    container_name: mini_etl_frontend
    ports:
      - "1936:1936"
    depends_on:
      - model
    env_file:
      - .env
    volumes:
      - ./src/staging:/app/src/staging
      - ./src/metadata:/app/src/metadata

  batch-worker:
    build:
      context: .
      dockerfile: src/batch/Dockerfile
    container_name: mini_etl_batch
    depends_on:
      - model
    volumes:
      - ./src/staging:/app/src/staging
      - ./src/metadata:/app/src/metadata

  streaming-worker:
    build:
      context: .
      dockerfile: src/streaming/Dockerfile
    container_name: mini_etl_stream
    depends_on:
      - model
    volumes:
      - ./src/metadata:/app/src/metadata
    ports:
      - "5001:5001"